name: Deploy Nextjs 14 to Azure

on:
  push:
    branches: ["main"]

  workflow_dispatch:

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read # This is required for actions/checkout

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: |
          npm install

      - name: 'Login to Azure Subscription' # This is required for OIDC authentication to Azure
        uses: azure/login@v1
        with:
            creds: ${{ secrets.AZURE_CREDENTIALS }}
            allow-no-subscriptions: true
          

      - name: Build Next.js app
        run: |
          npm run build
          mv .next/static .next/standalone/.next/static
          # mv public .next/standalone/public

      - name: Deploy
        shell: pwsh
        run: |
            $ZIP_FILE_NAME = "./${FILE_NAME}.zip"
            zip $ZIP_FILE_NAME ./* .next -qr

            az webapp deploy `
                --resource-group $RESOURCE_GROUP_NAME `
                --name $WEB_APP_NAME `
                --src-path $ZIP_FILE_NAME `
                --slot staging `
                --type zip `
                --clean true 

        env:
            FILE_NAME: "release"
            RESOURCE_GROUP_NAME: "appsvc_linux_centralus"
            WEB_APP_NAME: "chatbok"
